"use client";
import { use, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ExternalLink, Square, Copy, Download } from "lucide-react";
import { cancelResearch, getResearch, getSources } from "../../../lib/api";
import { useResearchEvents } from "../../../hooks/useResearchEvents";
import type { Research, Source } from "../../../types/research";
import ResearchProgress from "../../../components/research/ResearchProgress";
import AgentTimeline from "../../../components/research/AgentTimeline";
import StatusBadge from "../../../components/ui/StatusBadge";

export default function ResearchPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const [research, setResearch] = useState<Research | null>(null); const [sources, setSources] = useState<Source[]>([]); const [error, setError] = useState(""); const [copied, setCopied] = useState(false);
  const { events, connected, error: streamError } = useResearchEvents(id, research?.status !== "completed" && research?.status !== "failed" && research?.status !== "cancelled");
  useEffect(() => { Promise.all([getResearch(id), getSources(id)]).then(([item, sourceItems]) => { setResearch(item); setSources(sourceItems); }).catch(err => setError(err instanceof Error ? err.message : "Unable to load research.")); }, [id]);
  useEffect(() => { if (!research || ["completed", "failed", "cancelled"].includes(research.status)) return; const timer = setInterval(() => { getResearch(id).then(setResearch).catch(() => undefined); getSources(id).then(setSources).catch(() => undefined); }, 2500); return () => clearInterval(timer); }, [id, research]);
  async function copyReport() { if (!research?.report) return; await navigator.clipboard.writeText(`${research.question}\n\n${research.report.executive_summary ?? ""}`); setCopied(true); setTimeout(() => setCopied(false), 1600); }
  async function cancel() { await cancelResearch(id); setResearch(current => current ? { ...current, status: "cancelled" } : current); }
  if (error) return <main className="page"><Link href="/" className="back-link"><ArrowLeft size={16}/> Back to research</Link><div className="error-panel"><h1>Research unavailable</h1><p>{error}</p><Link href="/" className="button button-dark">Start a new investigation</Link></div></main>;
  if (!research) return <main className="page"><div className="skeleton skeleton-title"/><div className="skeleton skeleton-block"/></main>;
  const eventTypes = events.map(event => event.type);
  return <main className="page research-page"><div className="research-top"><Link href="/" className="back-link"><ArrowLeft size={16}/> New research</Link><StatusBadge status={research.status}/></div><div className="question-heading"><div className="eyebrow">Research investigation</div><h1>{research.question}</h1><div className="meta-line">{research.depth} depth <span/> {sources.length} sources accepted <span/> {new Date(research.created_at).toLocaleDateString()}</div></div>{streamError && <div className="connection-warning">{streamError}</div>}<div className="workspace-grid"><div className="workspace-left"><ResearchProgress eventTypes={eventTypes} status={research.status}/><AgentTimeline events={events}/>{research.status === "running" || research.status === "queued" ? <button className="button button-quiet cancel-button" onClick={cancel}><Square size={14}/> Cancel research</button> : null}</div><section className="panel report-panel"><div className="panel-heading"><div><div className="section-kicker">Live research brief</div><h2>{research.report ? "Research report" : "Building your report"}</h2></div>{research.report && <div className="report-actions"><button title="Copy summary" onClick={copyReport}><Copy size={15}/>{copied ? "Copied" : "Copy"}</button><a title="Export markdown" href={`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000/api"}/research/${id}/export?format=markdown`}><Download size={15}/>Export</a></div>}</div>{research.report ? <Report report={research.report} sources={sources}/> : <div className="report-wait"><div className="loader-bar"/><h3>Following the evidence</h3><p>Search results, source analysis, and verification will collect here as the agents work.</p>{events.at(-1) && <div className="latest-event">{events.at(-1)?.message}</div>}</div>}</section><aside className="sources-panel"><div className="panel-heading"><div><div className="section-kicker">Evidence</div><h2>Sources <span className="count">{sources.length}</span></h2></div><span className={connected ? "connection connected" : "connection"}>{connected ? "Live" : "Offline"}</span></div>{sources.length ? sources.map(source => <SourceCard key={source.id} source={source}/>) : <p className="muted">Accepted sources will appear here.</p>}</aside></div></main>;
}
function SourceCard({ source }: { source: Source }) { return <article className="source-card"><div className="citation">[{String(source.citation_id).padStart(2, "0")}]</div><div className="source-body"><a href={source.url} target="_blank" rel="noreferrer">{source.title}<ExternalLink size={13}/></a><small>{source.domain}</small><div className="score-row"><span>Credibility <b>{Math.round(source.credibility)}%</b></span><span>Relevance <b>{Math.round(source.relevance)}%</b></span></div></div></article>; }
function Report({ report, sources }: { report: NonNullable<Research["report"]>; sources: Source[] }) { return <div className="report-content"><div className="confidence">Confidence <strong>{Math.round((report.confidence ?? 0) * 100)}%</strong></div><h3>Executive summary</h3><p>{report.executive_summary}</p><h3>Key findings</h3>{report.key_findings?.map((finding, index) => <article className="finding" key={`${finding.title}-${index}`}><h4>{finding.title} <span>{finding.citations?.map(citation => <a href={sources.find(source => source.citation_id === citation)?.url} target="_blank" rel="noreferrer" key={citation}>[{citation}]</a>)}</span></h4><p>{finding.detail}</p></article>)}<h3>Detailed analysis</h3><p>{report.detailed_analysis}</p><h3>Limitations</h3><p>{report.limitations}</p><h3>Conclusion</h3><p>{report.conclusion}</p></div>; }
