"use client";
import { FormEvent, useState } from "react";
import { ArrowUpRight, FileText, Globe2, Layers3 } from "lucide-react";
import { createResearch } from "../lib/api";
import type { ResearchDepth } from "../types/research";
const examples = ["Compare autonomous vehicle software in Germany and the United States", "What are the major battery recycling trends in Europe?", "Assess the evidence for open source AI regulation in 2025"];
export default function Home() {
 const [question,setQuestion]=useState(""); const [depth,setDepth]=useState<ResearchDepth>("standard"); const [sources,setSources]=useState(6); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function submit(event:FormEvent){event.preventDefault();if(question.trim().length<10)return setError("Write a research question with a little more detail.");setBusy(true);setError("");try{const research=await createResearch(question,depth,sources);window.location.href=`/research/${research.id}`;}catch(err){setError(err instanceof Error?err.message:"Unable to start research");setBusy(false);}}
 return <main className="page home-page"><div className="hero-grid"><section className="hero"><div className="eyebrow"><span className="eyebrow-mark"/>Evidence-led intelligence</div><h1>Research anything.<br/><em>Understand everything.</em></h1><p className="hero-copy">Atlas turns complex questions into traceable research briefs by searching the live web, reading sources, and showing where every finding came from.</p><form className="research-form" onSubmit={submit}><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask anything you want to research..." aria-label="Research question" rows={3}/><div className="form-footer"><div className="depth-control"><span>Depth</span>{(["quick","standard","deep"] as ResearchDepth[]).map(item=><button type="button" key={item} className={depth===item?"selected":""} onClick={()=>setDepth(item)}>{item}</button>)}</div><button className="button button-dark submit-button" disabled={busy}>{busy?"Starting research...":<>Start research <ArrowUpRight size={16}/></>}</button></div></form>{error&&<p role="alert" className="error-text">{error}</p>}<div className="control-row"><label><Globe2 size={15}/> Sources <select value={sources} onChange={e=>setSources(Number(e.target.value))}><option value={4}>4 sources</option><option value={6}>6 sources</option><option value={10}>10 sources</option></select></label><span><FileText size={15}/> English</span><span><Layers3 size={15}/> Live web</span></div><div className="examples">{examples.map(example=><button className="example" key={example} onClick={()=>setQuestion(example)}>{example}</button>)}</div></section><aside className="hero-aside"><div className="orbit"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-core"><span>AT</span><small>evidence<br/>engine</small></div><i className="orbit-node node-one"/><i className="orbit-node node-two"/><i className="orbit-node node-three"/></div><p>One question in.<br/><strong>A clearer world out.</strong></p></aside></div><section className="feature-grid"><article><span className="feature-number">01</span><h3>Traceable by design</h3><p>Every accepted source is scored, cited, and ready to inspect.</p></article><article><span className="feature-number">02</span><h3>Agents that keep moving</h3><p>Search, analysis, verification, and synthesis work as one loop.</p></article><article><span className="feature-number">03</span><h3>Honest about uncertainty</h3><p>Limitations and conflicting evidence stay visible in the final brief.</p></article></section></main>;
}
